### PR TITLE
chore: remove dead code

### PR DESCRIPTION
**Pull request by LorenzBischof**
Before on the services page:
2024-03-05T09:56:21,410627837+01:00

After:
2024-03-05T09:56:39,783987048+01:00

My goal is to improve the Largest Contentful Paint time, which is also relevant for SEO: https://pagespeed.web.dev/analysis/https-peakscale-ch/p65ec83uy0?form_factor=mobile

### CODE REVIEW

**Comment by LorenzBischof** [comment]
hmm. It seems the difference is not that huge :) The browser shows 1.52MB on Render. Not sure why the Hugo live preview generated such a small number. I guess it still makes sense to remove code, we are not using...

**Comment by johanngyger** [comment]
Cleaning up is great, but I like those animations. If you plan to merge the pages in one, then we can proceed.

As a side note: On render, the SVGs in the English version are broken.

**Comment by LorenzBischof** [comment]
> As a side note: On render, the SVGs in the English version are broken.
Interesting. Is Render using Hugo 0.123? When testing locally I can reproduce with Hugo 0.123, but not 0.122. Hugo changed quite a lot internally in the 0.123 release.

**Comment by johanngyger** [comment]
> > As a side note: On render, the SVGs in the English version are broken.
> 
> Interesting. Is Render using Hugo 0.123? When testing locally I can reproduce with Hugo 0.123, but not 0.122. Hugo changed quite a lot internally in the 0.123 release and the behavior seems to be a bug.

Render is indeed using hugo v0.123.6-92684f9a26838a46d1a81e3c250fef5207bcb735+extended linux/amd64 BuildDate=2024-02-28T18:29:40Z VendorInfo=gohugoio

The version can't be configureed. Maybe there's a better way to preview PRs? It doesn't have to be Render 😄

**Comment by johanngyger** [comment]
Looks great! I also like the Cloudflare approach. I'll disable Render.

One minor thing: If I switch to the English version and hit repeatedly on the logo, I'll get this: https://remove-dead-code.peakscale.pages.dev/en/en/en/en/

**Comment by LorenzBischof** [comment]
Fixed. The behavior on 0.123 is expected and a breaking change: https://github.com/gohugoio/hugo/issues/11654 We will stay on 0.122 for now and soon migrate the other html to a shortcode, which will fix the problem. We might also want an image render hook in the future to support referencing images in Markdown.

**Pull request merged**
